// Code generated by scripts/generate-contracts.mjs; DO NOT EDIT.
// Sources: contracts/json-schema/common/dtos.schema.json,
//          contracts/events/event-envelope.schema.json

export type Identifier = string;
export type Timestamp = string;
export type RequestId = string;
export type Actor = Record<string, string>;

export type ApiError = {
  code: string;
  details?: unknown;
  message: string;
  request_id?: RequestId;
};

export type CursorPage = {
  has_more: boolean;
  next_cursor?: string | null;
};

export type EventEnvelope<
  TPayload extends Record<string, unknown> = Record<string, unknown>,
> = {
  actor: Actor | null;
  causation_id: string | null;
  correlation_id: string | null;
  event_id: string;
  event_type: string;
  occurred_at: Timestamp;
  payload: TPayload;
  producer: string;
  project_id: string | null;
  schema_version: number;
};
