"""add citations and zotero_configs

Revision ID: a0b22258ba0a
Revises: 003_add_llm_prompts_to_teams
Create Date: 2026-05-15 11:24:40.027618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b22258ba0a'
down_revision: Union[str, None] = '003_add_llm_prompts_to_teams'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
